injectEnvironmentFiles:
  - .env?

nodeLinker: node-modules

# Vercel reports an error message when using corepack to install Yarn 4.X.
# https://community.vercel.com/t/yarn-4-support/877/10
yarnPath: .yarn/releases/yarn-4.13.0.cjs
